apiVersion: v1
appVersion: "2.0.1"
description: ArkID is an enterprise SSO solutions, it supports LDAP, OpenID, SAML, OAuth and more
name: arkid
version: 2.0.1
maintainers:
- email: 494919572@qq.com
  name: jiashuai
home: https://github.com/longguikeji/arkid-charts
icon: https://raw.githubusercontent.com/skoogi/charts/assets/assets/logo.png
