apiVersion: v2
name: arkid
description: ArkID is an enterprise SSO solutions, it supports LDAP, OpenID, SAML, OAuth and more
type: application
version: 2.0.0
appVersion: "2.0.0"
keywords:
  - arkid
  - SSO
home: https://saas.arkid.cc/
sources:
  - https://github.com/longguikeji/arkid
  - https://github.com/longguikeji/arkid-frontend
maintainers:
- email: jiashuai@longguikeji.com
  name: notevery
icon: https://raw.githubusercontent.com/longguikeji/arkid-charts/chart/assets/arkidlogo.png
