imagePullSecrets:


# 持久化
persistence:  # mysql
  init: false
  storageClass:
  accessMode: ReadWriteOnce
  size: 8Gi

mysql:
  enabled: true
  image: mysql:5.7
  pullPolicy: IfNotPresent
  rootPassword: root
  database: arkid
  ## 主机标签
  ## 要符合json格式，如：
  ## {
  ##   "nfs": "true",
  ##   "ip": "111.111.111.111"
  ## }
  nodeSelector: {} 
  # Affinity rules for scheduling Pods of this StatefulSet on Nodes.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity
  nodeAffinity: {}
  # Inter-Pod Affinity rules for scheduling Pods of this StatefulSet.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  podAffinity: {}
  # Anti-affinity rules for scheduling Pods of this StatefulSet.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  # You may either toggle options below for default anti-affinity rules,
  # or specify the whole set of anti-affinity rules instead of them.
  podAntiAffinity: {}

externalDatabase:
  host: ""
  port: 3306
  database: ""
  user: ""
  password: ""

redis:
  enabled: true
  image: redis:5.0.3
  pullPolicy: IfNotPresent
  ## 主机标签
  ## 要符合json格式，如：
  ## {
  ##   "nfs": "true",
  ##   "ip": "111.111.111.111"
  ## }
  nodeSelector: {}
  # Affinity rules for scheduling Pods of this StatefulSet on Nodes.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity
  nodeAffinity: {}
  # Inter-Pod Affinity rules for scheduling Pods of this StatefulSet.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  podAffinity: {}
  # Anti-affinity rules for scheduling Pods of this StatefulSet.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  # You may either toggle options below for default anti-affinity rules,
  # or specify the whole set of anti-affinity rules instead of them.
  podAntiAffinity: {}

externalRedis:
  host: ""
  port: 6379
  db: 0

ldap:
  image: longguikeji/arkid_ldap_server:v2dev
  pullPolicy: IfNotPresent
  ## service 的类型，ClusterIP, NodePort, LoadBalancer
  svcType: NodePort
  # 当svcType为NodePort时有效，ldap 389暴露到nodePort的端口, 留空则会随机挑选一个端口
  nodePort389: 30189
  ## 主机标签
  ## 要符合json格式，如：
  ## {
  ##   "nfs": "true",
  ##   "ip": "111.111.111.111"
  ## }
  nodeSelector: {}
  # Affinity rules for scheduling Pods of this StatefulSet on Nodes.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity
  nodeAffinity: {}
  # Inter-Pod Affinity rules for scheduling Pods of this StatefulSet.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  podAffinity: {}
  # Anti-affinity rules for scheduling Pods of this StatefulSet.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  # You may either toggle options below for default anti-affinity rules,
  # or specify the whole set of anti-affinity rules instead of them.
  podAntiAffinity: {}
  
be:
  image: longguikeji/arkid:v2dev
  pullPolicy: IfNotPresent
  ## {  "limits": {"cpu": "800m","memory": "1024Mi"},"requests": {"cpu": "200m","memory": "256Mi"}}
  resources:
    limits: {}
    requests: {"cpu": "300m","memory": "1024Mi"}
  replicas: 1
  ## 主机标签
  ## 要符合json格式，如：
  ## {
  ##   "nfs": "true",
  ##   "ip": "111.111.111.111"
  ## }
  nodeSelector: {}
  # Affinity rules for scheduling Pods of this StatefulSet on Nodes.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity
  nodeAffinity: {}
  # Inter-Pod Affinity rules for scheduling Pods of this StatefulSet.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  podAffinity: {}
  # Anti-affinity rules for scheduling Pods of this StatefulSet.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  # You may either toggle options below for default anti-affinity rules,
  # or specify the whole set of anti-affinity rules instead of them.
  podAntiAffinity:
    # Type of anti-affinity rules: either `soft`, `hard` or empty value (which
    # disables anti-affinity rules).
    type: soft
    # Weight for `soft` anti-affinity rules.
    # Does not apply for other anti-affinity types.
    weight: 100

fe:
  image: longguikeji/arkid-fe:v2dev
  pullPolicy: IfNotPresent
  ## {  "limits": {"cpu": "800m","memory": "1024Mi"},"requests": {"cpu": "200m","memory": "256Mi"}}
  resources:
    limits: {}
    requests: {"cpu": "200m","memory": "1024Mi"}
  replicas: 1
  ## 主机标签
  ## 要符合json格式，如：
  ## {
  ##   "nfs": "true",
  ##   "ip": "111.111.111.111"
  ## }
  nodeSelector: {}
  # Affinity rules for scheduling Pods of this StatefulSet on Nodes.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity
  nodeAffinity: {}
  # Inter-Pod Affinity rules for scheduling Pods of this StatefulSet.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  podAffinity: {}
  # Anti-affinity rules for scheduling Pods of this StatefulSet.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  # You may either toggle options below for default anti-affinity rules,
  # or specify the whole set of anti-affinity rules instead of them.
  podAntiAffinity:
    # Type of anti-affinity rules: either `soft`, `hard` or empty value (which
    # disables anti-affinity rules).
    type: soft
    # Weight for `soft` anti-affinity rules.
    # Does not apply for other anti-affinity types.
    weight: 100

# webServerBroker:
#   ## 如果单独部署arkid，那么arkOS留空, webServerBroker 下的参数都不用填了；
#   ## 否则填写arkOS的api地址：例如：http://ark-apisvr
#   arkOS:
#   name: web-server-broker
#   image: longguikeji/arkid-broker:1.0.0
#   pullPolicy: IfNotPresent
#   port: 8080

portal:
  image: nginx:alpine
  pullPolicy: IfNotPresent
  ## service 的类型，ClusterIP, NodePort, LoadBalancer
  svcType: ClusterIP
  ## 主机标签
  ## 要符合json格式，如：
  ## {
  ##   "nfs": "true",
  ##   "ip": "111.111.111.111"
  ## }
  nodeSelector: {}
  # Affinity rules for scheduling Pods of this StatefulSet on Nodes.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity
  nodeAffinity: {}
  # Inter-Pod Affinity rules for scheduling Pods of this StatefulSet.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  podAffinity: {}
  # Anti-affinity rules for scheduling Pods of this StatefulSet.
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  # You may either toggle options below for default anti-affinity rules,
  # or specify the whole set of anti-affinity rules instead of them.
  podAntiAffinity: {}

celery:
  ## 定时任务，定制化功能
  enabled: false
  ## 主机标签
  ## 要符合json格式，如：
  ## {
  ##   "nfs": "true",
  ##   "ip": "111.111.111.111"
  ## }
  nodeSelector: {}
  resources:
    limits: {}
    requests: {"cpu": "200m","memory": "1024Mi"}


nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  # cert-manager 
  cert: false
  # 为空则使用 cert-manager生成的证书，不为空则使用指定的证书
  secret:
  annotations: {"kubernetes.io/ingress.class": "nginx","certmanager.k8s.io/cluster-issuer": "letsencrypt-prod"}
  host:
    # 需要DNS解析到ingress的ip
    # 本地调试就在 /etc/hosts里配置一下
    name: arkid.longguikeji.com
  # 如果没有 cert-manager，tls为true则helm会生成一个自签名的证书存到secret
  tls: true

ingressroute:
  enabled: false
  host:
    # 需要DNS解析到ingress的ip
    # 本地调试就在 /etc/hosts里配置一下
    name: arkid.longguikeji.com
  tls: 
    enabled: true
    certResolver:

ha:
  enabled: true
