{{- if false }}
apiVersion: {{ template "cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: clean-arkid-demo-for-public
spec:
  schedule: "59 1 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clean-arkid-demo-for-public
            image: busybox
            args:
                - /bin/sh
                - '-c'
                - 'date=`date`&&kubectl --kubeconfig=/tmp/config patch deploy arkid-demo-for-public-mysql arkid-demo-for-public-be arkid-demo-for-public-fe -n demo-for-public  --patch "{\"spec\": {\"template\": {\"metadata\": {\"annotations\": {\"restart/cleantime\": \"${date}\" }}}}}"'
            volumeMounts:
                - mountPath: /usr/bin/kubectl
                  name: hostkubectl
                - mountPath: /tmp/config
                  name: hostconfig
          restartPolicy: OnFailure
          nodeSelector:
            kubernetes.io/hostname: ark-prod-server001
          volumes:
            - name: hostkubectl
              hostPath:
                path: /usr/bin/kubectl
                type: File
            - name: hostconfig
              hostPath:
                path: /root/.kube/config
                type: File
{{- end }}