---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "arkid.fullname" . }}-fe"
  labels:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-fe"
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.fe.svcType }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-fe"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "arkid.fullname" . }}-fe"
  labels:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-fe"
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "arkid.name" . }}-fe"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "arkid.name" . }}-fe"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      initContainers:
      - command:
          - /bin/sh
          - '-c'
          - "until nc -z -w 2 {{ include "arkid.fullname" . }}-be 80 && echo {{ include "arkid.fullname" . }}-be ok; do sleep 2; done;"
        image: busybox
        imagePullPolicy: IfNotPresent
        name: check-all
      containers:
        - name: "{{ .Chart.Name }}-fe"
          image: "{{ .Values.fe.image }}"
          imagePullPolicy: {{ .Values.fe.pullPolicy }}
          env:
            - name: TZ
              value: 'Asia/Shanghai'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      {{if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
