{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arkid.redis.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "arkid.redis.fullname" . }}
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: tcp6379
  selector:
    app.kubernetes.io/name: {{ include "arkid.redis.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arkid.redis.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "arkid.redis.fullname" . }}
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arkid.redis.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arkid.redis.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - image: busybox
        command:
        - sh
        - -c
        - echo 65535 > /proc/sys/net/core/somaxconn
        imagePullPolicy: Always
        name: setsysctl
        securityContext:
          privileged: true
      containers:
        - name: {{ include "arkid.redis.fullname" . }}
          image: "{{ .Values.redis.image }}"
          imagePullPolicy: {{ .Values.redis.pullPolicy }}
          env:
            - name: TZ
              value: 'Asia/Shanghai'
      {{if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
{{- end }}