apiVersion: v1
kind: Service
metadata:
  name: {{ include "arkid.fullname" . }}-ldapjs
  labels:
    app.kubernetes.io/name: {{ include "arkid.name" . }}-ldapjs
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.ldap.svcType }}
  ports:
    - name: ldap
      port: 389
      {{- if .Values.ldap.nodePort }}
      nodePort: {{ .Values.ldap.nodePort389 }}
      {{- end }}
      targetPort: 1389
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "arkid.name" . }}-ldapjs
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "arkid.name" . }}-ldapjs
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "arkid.fullname" . }}-ldapjs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arkid.name" . }}-ldapjs
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arkid.name" . }}-ldapjs
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - image: busybox
        command:
        - sh
        - -c
        - sysctl -w net.core.somaxconn=65535
        imagePullPolicy: Always
        name: setsysctl
        securityContext:
          privileged: true
      - command:
          - /bin/sh
          - '-c'
          - "until nc -z -w 2 {{ include "arkid.fullname" . }}-be 80 && echo {{ include "arkid.fullname" . }}-be ok; do sleep 2; done;"
        image: busybox
        imagePullPolicy: IfNotPresent
        name: check-be
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        image: "{{ .Values.ldap.image }}"
        imagePullPolicy: {{ .Values.ldap.pullPolicy }}
        name: "{{ .Chart.Name }}-ldapjs"
        volumeMounts:
        - mountPath: /usr/src/app/config.json
          name: settings-local
          subPath: config.json
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ template "arkid.fullname" . }}
        name: settings-local
