version: '3.5'

services:
  portal:
    image: nginx:alpine
    container_name: ${INSTANCE}-portal
    restart: always
    networks:
      - arkid
    ports:
      - 8989:80
    depends_on:
      - be
      - fe
    volumes:
      - ${WORKSPACE}/portal.conf:/etc/nginx/conf.d/default.conf

  be:
    image: longguikeji/arkid:v2dev
    container_name: ${INSTANCE}-be
    sysctls:
      - net.core.somaxconn=65535
    restart: always
    environment:
      - MYSQL_HOST=${INSTANCE}-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=arkid
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - REDIS_HOST=${INSTANCE}-redis
    networks:
      - arkid
    depends_on:
      - db
    volumes:
      - ${WORKSPACE}/settings_local.py:/var/arkid/settings_local.py
      - ${WORKSPACE}/arkid.local.toml:/var/arkid/arkid.local.toml
      - ${WORKSPACE}/be:/data

  fe:
    image: longguikeji/arkid-fe:v2dev
    container_name: ${INSTANCE}-fe
    restart: always
    networks:
      - arkid
    volumes:
      - ${WORKSPACE}/fe.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    container_name: ${INSTANCE}-db
    restart: always
    networks:
      - arkid
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=arkid
    volumes:
      - ${WORKSPACE}/db/data:/var/lib/mysql
      - ${WORKSPACE}/db/config:/etc/mysql/conf.d
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  ldap:
    image: longguikeji/ark-sql-ldap:1.3.0
    container_name: ${INSTANCE}-ldap
    restart: always
    networks:
      - arkid
    depends_on:
      - be
    ports:
      - ${LDAP_PORT}:389
    environment:
      - SQL_HOST=${INSTANCE}-db
      - SQL_PORT=3306
      - SQL_USER=${MYSQL_USER}
      - SQL_PWD=${MYSQL_PASSWORD}
      - LDAP_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - SQL_DB=arkid
      - BACKEND=sql
      - SLAPD_NOFILE_SOFT=10000

  redis:
    image: redis:5.0.3
    container_name: ${INSTANCE}-redis
    restart: always
    networks:
      - arkid

networks:
  arkid:
    name: ${INSTANCE}
    driver: bridge
